#!/bin/bash

docker run -it --rm -e PYTHONPATH=/home/synergia/build/synergia2/src --mount type=bind,src=/etc/passwd,dst=/etc/passwd,readonly --mount type=bind,src=/etc/group,dst=/etc/group,readonly --mount type=bind,src=/etc/shadow,dst=/etc/shadow,readonly --mount type=bind,src=/etc/sudoers.d,dst=/etc/sudoers.d,readonly --mount type=bind,src=/tmp/.X11-unix,dst=/tmp/.X11-unix --mount type=bind,src=${PWD},dst=/home/workdir --user $(id -u):$(id -g) --privileged fnalacceleratormodeling/synergia3:latest /usr/bin/python3 "$@"
